[default]
run_cnt = 100
Max_iter = 50
BF_BDAY = '04/09/1958'
Death_age = 95
End_age = 101

[ConfigurationManager]
PLT_STYLE = 'seaborn-v0_8-deep'

[Cashflow]
Goals_file = "./Data/Envision_Goals.xlsx"
Default_inflation_rate = 2.5e-2  # 2.5 %