[default_values]
run_cnt = 100
seed = 42
re_alloc_error = 1e-6
nb_cpu = 4
Funds_step = 1e5
Discret_step = 0.01
Success_threshold = 1.0
Max_iter = 50

[user_data]
start_funds = 4.0e6
target_end_funds = 1e5
default_inflation_rate = 0.03
target_success_rate = 80
goals_file = "./Data/Envision_Goals.xlsx"
Death_age = 95
End_age = 101

[pfolio_alloc]
Stocks = 0.80
Bonds = 0.1
TBills = 0.1
Cash = 0.0
