[default]
run_cnt = 100
Max_iter = 50
BF_BDAY = '04/09/1958'
End_age = 101

[MonteCarloMulti]
seed = 42
re_alloc_error = 1e-6
nb_cpu = 4
Funds_step = 1e5
Discret_step = 0.01
Success_threshold = 1.0

[ConfigurationManager]
goals_file = "./Data/Envision_Goals.xlsx"
PLT_STYLE = 'seaborn-v0_8-deep'

[Portfolio]
start_funds = 4.0e6
target_end_funds = 1e5
default_inflation_rate = 0.03
target_success_rate = 80
Death_age = 95

[pfolio_alloc]
Stocks = 0.80
Bonds = 0.1
TBills = 0.1
Cash = 0.0

[MorningstarStats]
must_have_param = ['url_stats', 'url_corr', 'nb_smpl', 'model_file', 'xl_out_name']
XLabelLen = 5  # Length of the X axis labels
quick_flag = false
url_corr = "https://admainnew.morningstar.com/webhelp/Practice/Plans/Correlation_Matrix_of_the_14_Asset_Classes.htm"
url_stats = "https://admainnew.morningstar.com/webhelp/dialog_boxes/cs_db_editassumptions.htm"
nb_smpl = 1000000
validate_cross_correlation_flag = true
validation_error_margin = 1e-3 
model_file = "./Data/Morningstar_Asset_Stats/Models.xlsx"
xl_out_name = "./Data/Morningstar_asset_stats"

# Dict to map the Morningstar asset statistics labels to those of Morningstar Correlations
STAT_CORR_NAME_MAP = [
        ["US Large Cap Growth", "U.S. Lg Cap Growth"],
        ["US Large Cap Value", "U.S. Lg Cap Val"],
        ["US Mid Cap Growth", "U.S. Mid Cap Growth"],
        ["US Mid Cap Value",  "U.S. Mid Cap Val"],
        ["US Small Cap Growth", "U.S. Sm Cap Growth"],
        ["US Small Cap Value", "U.S. Sm Cap Val"],
        ["Non-US Dev Stk", "Foreign Industrialzed Mkts Stocks"],
        ["Non-US Emrg Stk", "Emerging Mkts Stks"], 
        ["US Inv Grade Bonds", "U.S. Investment Grade Bonds"],
        ["US High Yield Bonds", "U.S. High Yield Bonds"],
        ["Non-US Dev Bonds", "Non-U.S. Bonds"],
        ["Cash", "Cash"],
        ["Commodities", "Commodities"],
        ["Real Estate", "Real Estate"]
]


